import type { PrintRecord, WpMedia, WpPost, WpPostEdit, WpPostType } from '@dbp-wp/core';
import type {
  ConnectionStatus,
  ImportCreateInput,
  ImportResult,
  MediaListResult,
  MetaDeletion,
  PostBodyUpdate,
  PostUpdate,
  PostsResponse,
  PrintRecordsResponse,
  UpdateResult,
} from './api.types';
import { DEMO_COUNTRIES, DEMO_REGIONS } from './demo-seed';

// Browser-demo data layer: an in-memory, network-free store seeded from open data. It
// implements the same surface as `api.cli.ts` but never touches a real WordPress site or
// the CLI, so the demo holds no credentials and sends nothing anywhere. State resets on
// reload — a clean slate each visit, which is what a demo wants.
//
// The seed (src/lib/demo-seed.ts, generated by scripts/build-demo-seed.mjs) is World Bank
// Open Data (CC BY 4.0) for the most-populous ~50 countries, plus their World Bank regions
// as a second post type. Each country's parent is its region, demonstrating cross-type
// parent/child relations on real data; flags ride along as the featured image (thumbnail).

/** REST route bases for the two demo post types. */
const COUNTRY_TYPE = 'posts'; // the default tab in App.svelte
const REGION_TYPE = 'regions';

/** An in-memory demo record carrying everything the spreadsheet and Print views need. */
interface DemoRecord {
  id: number;
  type: string; // REST route base (COUNTRY_TYPE | REGION_TYPE)
  title: string;
  status: string;
  menuOrder: number;
  content: string;
  excerpt: string;
  featuredImageUrl: string;
  /** Featured media id (into the demo media store), mirroring `featured_media` in full mode. */
  featuredMedia?: number;
  meta: Record<string, string>;
  tax: Record<string, string[]>;
  parent?: number;
  parentType?: string;
  /** Lossless Markdown source (Markdown-mode posts only), mirroring `_dbp_wp_markdown`. */
  markdown?: string;
}

/** An in-memory demo media item (shape-compatible with {@link WpMedia}). */
interface DemoMedia {
  id: number;
  sourceUrl: string;
  thumbnailUrl: string;
  title: string;
  mimeType: string;
}

/** Media ids live in their own range so they never collide with demo post ids. */
const MEDIA_ID_BASE = 10001;

// A tiny inline placeholder so a region (no flag) never makes a network request.
const PLACEHOLDER_IMAGE =
  'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22120%22%20height%3D%2280%22%3E%3Crect%20width%3D%22120%22%20height%3D%2280%22%20fill%3D%22%23e2e8f0%22%2F%3E%3C%2Fsvg%3E';

/** Format an integer-ish indicator as a plain string for an editable meta field. */
function num(value: number | null): string {
  return value === null ? '' : String(Math.round(value));
}

function seed(): DemoRecord[] {
  const regions: DemoRecord[] = DEMO_REGIONS.map((r, i) => ({
    id: r.id,
    type: REGION_TYPE,
    title: r.name,
    status: 'publish',
    menuOrder: i + 1,
    content: `<p>${r.name}: a World Bank region grouping the countries below.</p>`,
    excerpt: `<p>${r.name}.</p>`,
    featuredImageUrl: PLACEHOLDER_IMAGE,
    meta: {},
    tax: { region: [r.name] },
  }));

  const countries: DemoRecord[] = DEMO_COUNTRIES.map((c, i) => ({
    id: c.id,
    type: COUNTRY_TYPE,
    title: c.name,
    status: 'publish',
    menuOrder: c.menuOrder,
    content: `<p>${c.name} — capital ${c.capital || 'n/a'}, ${c.region}.</p>`,
    excerpt: `<p>${c.name}</p>`,
    featuredImageUrl: c.flag,
    // The flag rides as the featured image; its media id matches seedMedia()'s id scheme.
    featuredMedia: MEDIA_ID_BASE + i,
    meta: {
      iso2: c.iso2,
      capital: c.capital,
      region: c.region,
      income_level: c.incomeLevel,
      population: num(c.population),
      gdp_usd: num(c.gdp),
      gdp_per_capita_usd: num(c.gdpPerCapita),
      surface_area_km2: num(c.surfaceArea),
    },
    tax: { region: [c.region], income: c.incomeLevel ? [c.incomeLevel] : [] },
    ...(c.parentRegionId !== null
      ? { parent: c.parentRegionId, parentType: REGION_TYPE }
      : {}),
  }));

  return [...countries, ...regions];
}

/** Seed the media library from the country flags, with ids matching seed()'s scheme. */
function seedMedia(): DemoMedia[] {
  return DEMO_COUNTRIES.map((c, i) => ({
    id: MEDIA_ID_BASE + i,
    sourceUrl: c.flag,
    thumbnailUrl: c.flag,
    title: `${c.name} flag`,
    mimeType: 'image/png',
  }));
}

const store: DemoRecord[] = seed();
const mediaStore: DemoMedia[] = seedMedia();
let nextId = Math.max(...store.map((r) => r.id)) + 1;
let nextMediaId = Math.max(MEDIA_ID_BASE - 1, ...mediaStore.map((m) => m.id)) + 1;

function toWpPost(d: DemoRecord): WpPost {
  // The demo presents as a connector-active site, so meta lives under dbpWpMeta (the
  // spreadsheet's editable meta columns).
  const post: WpPost = {
    id: d.id,
    type: d.type === REGION_TYPE ? 'region' : 'country',
    status: d.status,
    title: d.title,
    menuOrder: d.menuOrder,
    meta: {},
    dbpWpMeta: { ...d.meta },
  };
  if (d.parent !== undefined) {
    post.parent = d.parent;
  }
  if (d.parentType !== undefined) {
    post.parentType = d.parentType;
  }
  if (d.featuredMedia !== undefined) {
    post.featuredMedia = d.featuredMedia;
  }
  return post;
}

function toWpMedia(m: DemoMedia): WpMedia {
  return { ...m };
}

/** Build the body-editing model for a demo record (mode follows a non-empty Markdown source). */
function toWpPostEdit(d: DemoRecord): WpPostEdit {
  const edit: WpPostEdit = {
    id: d.id,
    type: d.type === REGION_TYPE ? 'region' : 'country',
    status: d.status,
    title: d.title,
    content: d.content,
  };
  if (typeof d.markdown === 'string' && d.markdown !== '') {
    edit.markdown = d.markdown;
  }
  return edit;
}

function toPrintRecord(d: DemoRecord): PrintRecord {
  return {
    id: d.id,
    title: d.title,
    content: d.content,
    excerpt: d.excerpt,
    status: d.status,
    menuOrder: d.menuOrder,
    featuredImageUrl: d.featuredImageUrl,
    meta: { ...d.meta },
    tax: { region: [...(d.tax.region ?? [])], income: [...(d.tax.income ?? [])] },
  };
}

function byType(type: string | undefined): DemoRecord[] {
  const t = type ?? COUNTRY_TYPE;
  return store.filter((r) => r.type === t);
}

function find(id: number): DemoRecord | undefined {
  return store.find((p) => p.id === id);
}

const CONNECTION: ConnectionStatus = {
  connected: true,
  siteUrl: 'demo://world-bank-open-data',
  connectorAvailable: true,
  // The demo never handles real credentials, so secure-storage persistence is irrelevant.
  canPersist: false,
  persisted: false,
  savedSiteUrl: null,
};

export function getConnection(): Promise<ConnectionStatus> {
  return Promise.resolve({ ...CONNECTION });
}

export function connect(): Promise<ConnectionStatus> {
  // The demo is always "connected" to its local store; credentials are ignored entirely.
  // (The CLI's `connect(input)` takes credentials; this fewer-arg form still satisfies ApiImpl.)
  return Promise.resolve({ ...CONNECTION });
}

/** The demo has no secure storage; "use saved" just returns the always-connected demo state. */
export function connectSaved(): Promise<ConnectionStatus> {
  return Promise.resolve({ ...CONNECTION });
}

export function disconnect(): Promise<void> {
  return Promise.resolve();
}

/** Nothing is ever persisted in the demo, so forgetting is a no-op. */
export function forget(): Promise<void> {
  return Promise.resolve();
}

export function fetchTypes(): Promise<WpPostType[]> {
  return Promise.resolve([
    { slug: 'country', restBase: COUNTRY_TYPE, name: 'Countries' },
    { slug: 'region', restBase: REGION_TYPE, name: 'Regions' },
  ]);
}

export function fetchPosts(query?: { type?: string }): Promise<PostsResponse> {
  return Promise.resolve({ posts: byType(query?.type).map(toWpPost), unconfigured: false });
}

export function fetchPost(id: number, _type: string): Promise<WpPostEdit> {
  const post = find(id);
  if (!post) {
    return Promise.reject(new Error('Not found in demo data'));
  }
  return Promise.resolve(toWpPostEdit(post));
}

export function savePostBody(
  id: number,
  _type: string,
  update: PostBodyUpdate,
): Promise<WpPostEdit> {
  const post = find(id);
  if (!post) {
    return Promise.reject(new Error('Not found in demo data'));
  }
  post.content = update.content;
  // A string sets the Markdown source; null clears it (HTML mode); undefined leaves it.
  if (update.markdown === null) {
    delete post.markdown;
  } else if (update.markdown !== undefined) {
    post.markdown = update.markdown;
  }
  return Promise.resolve(toWpPostEdit(post));
}

export function fetchPrintRecords(query?: { type?: string }): Promise<PrintRecordsResponse> {
  return Promise.resolve({ records: byType(query?.type).map(toPrintRecord), unconfigured: false });
}

export function savePosts(updates: PostUpdate[]): Promise<UpdateResult[]> {
  const results: UpdateResult[] = [];
  for (const update of updates) {
    const post = find(update.id);
    if (!post) {
      results.push({ id: update.id, ok: false, error: 'Not found in demo data' });
      continue;
    }
    if (update.title !== undefined) post.title = update.title;
    if (update.menuOrder !== undefined) post.menuOrder = update.menuOrder;
    if (update.status !== undefined) post.status = update.status;
    if (update.featuredMedia !== undefined) {
      if (update.featuredMedia === 0) {
        delete post.featuredMedia;
        post.featuredImageUrl = PLACEHOLDER_IMAGE;
      } else {
        post.featuredMedia = update.featuredMedia;
        // Mirror the URL onto the record so the Print view reflects the new featured image.
        const m = mediaStore.find((x) => x.id === update.featuredMedia);
        if (m) post.featuredImageUrl = m.sourceUrl;
      }
    }
    if (update.meta) {
      for (const [key, value] of Object.entries(update.meta)) {
        post.meta[key] = value == null ? '' : String(value);
      }
    }
    results.push({ id: update.id, ok: true });
  }
  return Promise.resolve(results);
}

export function importPosts(creates: ImportCreateInput[]): Promise<ImportResult[]> {
  const results: ImportResult[] = [];
  for (const [index, create] of creates.entries()) {
    const meta: Record<string, string> = {};
    if (create.meta) {
      for (const [key, value] of Object.entries(create.meta)) {
        meta[key] = value == null ? '' : String(value);
      }
    }
    const id = nextId++;
    store.push({
      id,
      type: COUNTRY_TYPE,
      title: create.title ?? '(untitled)',
      status: create.status ?? 'draft',
      menuOrder: create.menuOrder ?? 0,
      content: '',
      excerpt: '',
      featuredImageUrl: PLACEHOLDER_IMAGE,
      meta,
      tax: { region: [], income: [] },
    });
    results.push({ index, ok: true, id });
  }
  return Promise.resolve(results);
}

export function bulkDeleteMeta(deletes: MetaDeletion[]): Promise<UpdateResult[]> {
  const results: UpdateResult[] = [];
  for (const del of deletes) {
    const post = find(del.id);
    if (!post) {
      results.push({ id: del.id, ok: false, error: 'Not found in demo data' });
      continue;
    }
    for (const key of del.keys) {
      delete post.meta[key];
    }
    results.push({ id: del.id, ok: true });
  }
  return Promise.resolve(results);
}

export function setRelation(
  childId: number,
  _childType: string,
  parentId: number,
  parentType: string,
): Promise<WpPost> {
  const post = find(childId);
  if (!post) {
    return Promise.reject(new Error('Not found in demo data'));
  }
  if (parentId === childId) {
    return Promise.reject(new Error('A post cannot be its own parent.'));
  }
  post.parent = parentId;
  post.parentType = parentType;
  return Promise.resolve(toWpPost(post));
}

export function clearRelation(childId: number, _childType: string): Promise<WpPost> {
  const post = find(childId);
  if (!post) {
    return Promise.reject(new Error('Not found in demo data'));
  }
  delete post.parent;
  delete post.parentType;
  return Promise.resolve(toWpPost(post));
}

/** How many media items the demo picker shows per page. */
const MEDIA_PER_PAGE = 12;

/**
 * Upload a local file into the demo media store. Network-free: the file is read into a
 * data URL with FileReader and kept in memory only (nothing is sent anywhere), matching the
 * demo's "data stays in your browser" guarantee.
 */
export function uploadMedia(file: File): Promise<WpMedia> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const url = typeof reader.result === 'string' ? reader.result : '';
      const media: DemoMedia = {
        id: nextMediaId++,
        sourceUrl: url,
        thumbnailUrl: url,
        title: file.name,
        mimeType: file.type || 'application/octet-stream',
      };
      mediaStore.push(media);
      resolve(toWpMedia(media));
    };
    reader.onerror = () => reject(new Error('Could not read the file.'));
    reader.readAsDataURL(file);
  });
}

export function listMedia(query?: { page?: number; search?: string }): Promise<MediaListResult> {
  const search = query?.search?.trim().toLowerCase();
  // Newest first (uploads appear at the top), then optional title filter.
  const ordered = mediaStore.slice().reverse();
  const filtered = search ? ordered.filter((m) => m.title.toLowerCase().includes(search)) : ordered;
  const totalPages = Math.max(1, Math.ceil(filtered.length / MEDIA_PER_PAGE));
  const page = Math.min(Math.max(1, query?.page ?? 1), totalPages);
  const start = (page - 1) * MEDIA_PER_PAGE;
  return Promise.resolve({
    items: filtered.slice(start, start + MEDIA_PER_PAGE).map(toWpMedia),
    totalPages,
  });
}

export function resolveMedia(ids: number[]): Promise<WpMedia[]> {
  const wanted = new Set(ids);
  return Promise.resolve(mediaStore.filter((m) => wanted.has(m.id)).map(toWpMedia));
}
