import type { PrintRecord, WpPost, WpPostType } from '@dbp-wp/core';
import type {
  ConnectionStatus,
  ImportCreateInput,
  ImportResult,
  MetaDeletion,
  PostUpdate,
  PostsResponse,
  PrintRecordsResponse,
  UpdateResult,
} from './api.types';
import { DEMO_COUNTRIES, DEMO_REGIONS } from './demo-seed';

// Browser-demo data layer: an in-memory, network-free store seeded from open data. It
// implements the same surface as `api.cli.ts` but never touches a real WordPress site or
// the CLI, so the demo holds no credentials and sends nothing anywhere. State resets on
// reload — a clean slate each visit, which is what a demo wants.
//
// The seed (src/lib/demo-seed.ts, generated by scripts/build-demo-seed.mjs) is World Bank
// Open Data (CC BY 4.0) for the most-populous ~50 countries, plus their World Bank regions
// as a second post type. Each country's parent is its region, demonstrating cross-type
// parent/child relations on real data; flags ride along as the featured image (thumbnail).

/** REST route bases for the two demo post types. */
const COUNTRY_TYPE = 'posts'; // the default tab in App.svelte
const REGION_TYPE = 'regions';

/** An in-memory demo record carrying everything the spreadsheet and Print views need. */
interface DemoRecord {
  id: number;
  type: string; // REST route base (COUNTRY_TYPE | REGION_TYPE)
  title: string;
  status: string;
  menuOrder: number;
  content: string;
  excerpt: string;
  featuredImageUrl: string;
  meta: Record<string, string>;
  tax: Record<string, string[]>;
  parent?: number;
  parentType?: string;
}

// A tiny inline placeholder so a region (no flag) never makes a network request.
const PLACEHOLDER_IMAGE =
  'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22120%22%20height%3D%2280%22%3E%3Crect%20width%3D%22120%22%20height%3D%2280%22%20fill%3D%22%23e2e8f0%22%2F%3E%3C%2Fsvg%3E';

/** Format an integer-ish indicator as a plain string for an editable meta field. */
function num(value: number | null): string {
  return value === null ? '' : String(Math.round(value));
}

function seed(): DemoRecord[] {
  const regions: DemoRecord[] = DEMO_REGIONS.map((r, i) => ({
    id: r.id,
    type: REGION_TYPE,
    title: r.name,
    status: 'publish',
    menuOrder: i + 1,
    content: `<p>${r.name}: a World Bank region grouping the countries below.</p>`,
    excerpt: `<p>${r.name}.</p>`,
    featuredImageUrl: PLACEHOLDER_IMAGE,
    meta: {},
    tax: { region: [r.name] },
  }));

  const countries: DemoRecord[] = DEMO_COUNTRIES.map((c) => ({
    id: c.id,
    type: COUNTRY_TYPE,
    title: c.name,
    status: 'publish',
    menuOrder: c.menuOrder,
    content: `<p>${c.name} — capital ${c.capital || 'n/a'}, ${c.region}.</p>`,
    excerpt: `<p>${c.name}</p>`,
    featuredImageUrl: c.flag,
    meta: {
      iso2: c.iso2,
      capital: c.capital,
      region: c.region,
      income_level: c.incomeLevel,
      population: num(c.population),
      gdp_usd: num(c.gdp),
      gdp_per_capita_usd: num(c.gdpPerCapita),
      surface_area_km2: num(c.surfaceArea),
    },
    tax: { region: [c.region], income: c.incomeLevel ? [c.incomeLevel] : [] },
    ...(c.parentRegionId !== null
      ? { parent: c.parentRegionId, parentType: REGION_TYPE }
      : {}),
  }));

  return [...countries, ...regions];
}

const store: DemoRecord[] = seed();
let nextId = Math.max(...store.map((r) => r.id)) + 1;

function toWpPost(d: DemoRecord): WpPost {
  // The demo presents as a connector-active site, so meta lives under dbpWpMeta (the
  // spreadsheet's editable meta columns).
  const post: WpPost = {
    id: d.id,
    type: d.type === REGION_TYPE ? 'region' : 'country',
    status: d.status,
    title: d.title,
    menuOrder: d.menuOrder,
    meta: {},
    dbpWpMeta: { ...d.meta },
  };
  if (d.parent !== undefined) {
    post.parent = d.parent;
  }
  if (d.parentType !== undefined) {
    post.parentType = d.parentType;
  }
  return post;
}

function toPrintRecord(d: DemoRecord): PrintRecord {
  return {
    id: d.id,
    title: d.title,
    content: d.content,
    excerpt: d.excerpt,
    status: d.status,
    menuOrder: d.menuOrder,
    featuredImageUrl: d.featuredImageUrl,
    meta: { ...d.meta },
    tax: { region: [...(d.tax.region ?? [])], income: [...(d.tax.income ?? [])] },
  };
}

function byType(type: string | undefined): DemoRecord[] {
  const t = type ?? COUNTRY_TYPE;
  return store.filter((r) => r.type === t);
}

function find(id: number): DemoRecord | undefined {
  return store.find((p) => p.id === id);
}

const CONNECTION: ConnectionStatus = {
  connected: true,
  siteUrl: 'demo://world-bank-open-data',
  connectorAvailable: true,
};

export function getConnection(): Promise<ConnectionStatus> {
  return Promise.resolve({ ...CONNECTION });
}

export function connect(): Promise<ConnectionStatus> {
  // The demo is always "connected" to its local store; credentials are ignored entirely.
  // (The CLI's `connect(input)` takes credentials; this fewer-arg form still satisfies ApiImpl.)
  return Promise.resolve({ ...CONNECTION });
}

export function disconnect(): Promise<void> {
  return Promise.resolve();
}

export function fetchTypes(): Promise<WpPostType[]> {
  return Promise.resolve([
    { slug: 'country', restBase: COUNTRY_TYPE, name: 'Countries' },
    { slug: 'region', restBase: REGION_TYPE, name: 'Regions' },
  ]);
}

export function fetchPosts(query?: { type?: string }): Promise<PostsResponse> {
  return Promise.resolve({ posts: byType(query?.type).map(toWpPost), unconfigured: false });
}

export function fetchPrintRecords(query?: { type?: string }): Promise<PrintRecordsResponse> {
  return Promise.resolve({ records: byType(query?.type).map(toPrintRecord), unconfigured: false });
}

export function savePosts(updates: PostUpdate[]): Promise<UpdateResult[]> {
  const results: UpdateResult[] = [];
  for (const update of updates) {
    const post = find(update.id);
    if (!post) {
      results.push({ id: update.id, ok: false, error: 'Not found in demo data' });
      continue;
    }
    if (update.title !== undefined) post.title = update.title;
    if (update.menuOrder !== undefined) post.menuOrder = update.menuOrder;
    if (update.status !== undefined) post.status = update.status;
    if (update.meta) {
      for (const [key, value] of Object.entries(update.meta)) {
        post.meta[key] = value == null ? '' : String(value);
      }
    }
    results.push({ id: update.id, ok: true });
  }
  return Promise.resolve(results);
}

export function importPosts(creates: ImportCreateInput[]): Promise<ImportResult[]> {
  const results: ImportResult[] = [];
  for (const [index, create] of creates.entries()) {
    const meta: Record<string, string> = {};
    if (create.meta) {
      for (const [key, value] of Object.entries(create.meta)) {
        meta[key] = value == null ? '' : String(value);
      }
    }
    const id = nextId++;
    store.push({
      id,
      type: COUNTRY_TYPE,
      title: create.title ?? '(untitled)',
      status: create.status ?? 'draft',
      menuOrder: create.menuOrder ?? 0,
      content: '',
      excerpt: '',
      featuredImageUrl: PLACEHOLDER_IMAGE,
      meta,
      tax: { region: [], income: [] },
    });
    results.push({ index, ok: true, id });
  }
  return Promise.resolve(results);
}

export function bulkDeleteMeta(deletes: MetaDeletion[]): Promise<UpdateResult[]> {
  const results: UpdateResult[] = [];
  for (const del of deletes) {
    const post = find(del.id);
    if (!post) {
      results.push({ id: del.id, ok: false, error: 'Not found in demo data' });
      continue;
    }
    for (const key of del.keys) {
      delete post.meta[key];
    }
    results.push({ id: del.id, ok: true });
  }
  return Promise.resolve(results);
}

export function setRelation(
  childId: number,
  _childType: string,
  parentId: number,
  parentType: string,
): Promise<WpPost> {
  const post = find(childId);
  if (!post) {
    return Promise.reject(new Error('Not found in demo data'));
  }
  if (parentId === childId) {
    return Promise.reject(new Error('A post cannot be its own parent.'));
  }
  post.parent = parentId;
  post.parentType = parentType;
  return Promise.resolve(toWpPost(post));
}

export function clearRelation(childId: number, _childType: string): Promise<WpPost> {
  const post = find(childId);
  if (!post) {
    return Promise.reject(new Error('Not found in demo data'));
  }
  delete post.parent;
  delete post.parentType;
  return Promise.resolve(toWpPost(post));
}
